service: employee-management

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    API_PORT: ${env:API_PORT}
    DB_PORT: ${env:DB_PORT}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_NAME: ${env:DB_NAME}
    DB_SYNC: ${env:DB_SYNC}

functions:
  main:
    handler: dist/serverless.handler
    events: 
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
      