version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    ports:
      - 3001:3001
    command: npm run start
    deploy:
      resources:
        limits:
          memory: 250M

    depends_on:
        - db

volumes:
  db_data: