#!/bin/bash

# Create or overwrite the .env file
cat << EOF > .env
NODE_ENV=$NODE_ENV
API_PORT=$API_PORT
DB_PORT=$DB_PORT
DB_PASSWORD=$DB_PASSWORD
DB_HOST=$DB_HOST
DB_USERNAME=$DB_USERNAME
DB_NAME=$DB_NAME
DB_SYNC=$DB_SYNC
JWT_SECRET=$JWT_SECRET
JWT_EXPIRATION=$JWT_EXPIRATION
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
BUCKET_NAME=$BUCKET_NAME
BUCKET_URL=$BUCKET_URL
LOCAL_UPLOAD_FOLDER=$LOCAL_UPLOAD_FOLDER
EOF

echo ".env file created successfully."