# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: API Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy-digital-ocean:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
          node-version: 18.x

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Install Dependencies
      run: npm ci

    - name: Check API Directory
      run: |
        ssh root@${{ secrets.SSH_HOST }} <<'EOF'
        cd /var/www
        if [ -d "api" ]; then
          rm -rf api
        else
          echo "No existing api directory found. Skipping removal."
        fi
        mkdir -p api
        EOF

    - name: Build the project
      run: npm run build

    - name: Package Application
      run: tar -czf package.tar.gz dist node_modules
    
    - name: Starting Application on Production Server
      run: |
        ssh root@${{ secrets.SSH_HOST }} <<'EOF'
        echo "Navigating to the project directory..."
        cd /var/www/api || exit 1
        if [ -f "package.tar.gz" ]; then
          tar -xzf package.tar.gz
          rm package.tar.gz
        fi
        pm2 start dist/main.js
        EOF

