# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: API Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy-digital-ocean:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
          node-version: 18.x

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Install Dependencies
      run: npm install -g yarn && yarn install

    - name: Running Tests
      run: yarn test
    
    - name: Check API Directory
      run: |
        ssh root@${{ secrets.SSH_HOST }} <<'EOF'
        cd /var/www
        if [ -d "api" ]; then
          echo "Removing existing api directory..."
          rm -rf api
        else
          echo "No existing api directory found. Skipping removal."
        fi
        mkdir -p api # Ensure api directory exists for .env file

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
            envkey_NODE_ENV: ${{secrets.NODE_ENV}}
            envkey_API_PORT: ${{secrets.API_PORT}}
            envkey_DB_PORT: ${{secrets.DB_PORT}}
            envkey_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            envkey_DB_HOST: ${{secrets.DB_HOST}}
            envkey_DB_USERNAME: ${{secrets.DB_USERNAME}}
            envkey_DB_NAME: ${{secrets.DB_NAME}}
            envkey_DB_SYNC: ${{secrets.DB_SYNC}}
            envkey_DB_ENTITIES: ${{secrets.DB_ENTITIES}}
            envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
            envkey_JWT_EXPIRATION: ${{secrets.JWT_EXPIRATION}}
            envkey_JWT_REFRESH_SECRET: ${{secrets.JWT_REFRESH_SECRET}}
            envkey_JWT_REFRESH_EXPIRATION: ${{secrets.JWT_REFRESH_EXPIRATION}}
            envkey_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            envkey_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            envkey_AWS_REGION: ${{secrets.AWS_REGION}}
            envkey_BUCKET_NAME: ${{secrets.BUCKET_NAME}}
            envkey_BUCKET_URL: ${{secrets.BUCKET_URL}}
            envkey_LOCAL_UPLOAD_FOLDER: ${{secrets.LOCAL_UPLOAD_FOLDER}}
            file_name: .env
            directory: '.'
            fail_on_empty: false
            sort_keys: false
      
    - name: Transfer Env file
      run: scp .env root@${{ secrets.SSH_HOST }}:/var/www/api 

    - name: Deploy
      run: |
        ssh root@${{ secrets.SSH_HOST }} "chmod +x ~/deploy.sh && ~/deploy.sh"

