# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: API Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
          node-version: 18.x

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Install Dependencies
      run: npm ci

    - name: "Running Tests"
      run: npm run test
    
    - name: "Deploying to Server"
      run: |
        ssh root@${{ secrets.SSH_HOST }} 'cd~:backend/${{ github.event.repository.name }}'
        ssh root@${{ secrets.SSH_HOST }} 'chmod +x deploy.sh'
        ssh root@${{ secrets.SSH_HOST }} './deploy.sh'

    
